AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda Function.
Resources:
  helloworld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: src/
      Description: A starter AWS Lambda Function.
      MemorySize: 128
      Timeout: 3
      Events:
        HellowWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: GET